# This is a basic workflow to help you get started with Actions
env:
    GH_TOKEN: ${{ github.token }}
    REPO_NAME: ${{ secrets.REPOSITORY_NAME }}
    RELEASE_VERSION: "2020.1"
    RELEASE_BRANCH: ${{ secrets.RELEASE_20_1_BRANCH }}
    REPO_URL: ${{ secrets.REPO_URL }}
    TEAMS_WEBHOOK: ${{ secrets.TEAMS_WEBHOOK }}
    API_KEY: ${{ secrets.API_KEY }}

name: BranchUpdaterAction

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    permissions:
        contents: write
        pull-requests: write
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script  
        run: |
          set +e
          repositoryName=$REPO_NAME
          releaseBranchName=$RELEASE_BRANCH
          releaseVersion=$RELEASE_VERSION
          repoUrl=$REPO_URL
          webhookUrl=$TEAMS_WEBHOOK
          apiKey=$API_KEY

          curl "gssgit.gss-service.com/api/GitBranchUpdater?repoName=${repositoryName}&releaseBranch=${releaseBranchName}&releaseVersion=${releaseVersion}&repoUrl=${repoUrl}&webhookUrl=${webhookUrl}&apiKey=${apiKey}"

          exit 0
          
