# This is a basic workflow to help you get started with Actions
env:
    GH_TOKEN: ${{ github.token }}

name: BranchUpdaterAction

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    permissions:
        contents: write
        pull-requests: write
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          set +e
          repositoryName="TestFeatureBranchUpdater"
          releaseBranchName="main"
          releaseVersion="2020.1"
          repoUrl="https://github.com/sharris-gss/TestFeatureBranchUpdater.git"
          webhookUrl="https://gssmail.webhook.office.com/webhookb2/9417b749-cee1-45e5-b7f1-692f25c9dbb4@9be26962-4b1b-41b8-92b1-4bfb10ce22cf/IncomingWebhook/352223b2ccab401f961c4e757014101d/ddb00d94-91a5-4216-b1d9-2c4261ae3f21"
          apiKey="eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhcGlrZXkiOiJhcGlLZXkiLCJnaXRBdXRoVG9rZW4iOiJ0b2tlblZhbHVlIn0.jtnJIjlh22i0R27zRgTUolLS2JSjNjCHiC0AVhbKS26kradbTJqUHVaD_sFd0W0tQLgY84Z12awp89Fw0d4EVg"

          curl "gssgit.gss-service.com/api/GitBranchUpdater?repoName=${repositoryName}&releaseBranch=${releaseBranchName}&releaseVersion=${releaseVersion}&repoUrl=${repoUrl}&webhookUrl=${webhookUrl}&apiKey=${apiKey}"

          exit 0
          
